### ISSUE TITLE
Missing eslint rules

### ISSUE THREAD

**Issue by joelnet** [joelnet/eslint-config-mojiscript#1]
`no-if` - prevent if statements.
`max-param-call` - similar to max-param, but limit arguments to calls to 1 param.

**Comment by luizbills** [comment]
this eslint-plugin has a `no-if` rule.
https://github.com/idmitriev/eslint-plugin-better

**Comment by joelnet** [comment]
Great find. I searched and couldn't find this.

**Comment by luizbills** [comment]
in eslint has some issues that can preclude this `max-param-call` rule
https://stackoverflow.com/a/48639383

**Comment by joelnet** [comment]
I don't think that issue would be the same. The SO article is attempting to determine how many arguments are in the function and then limit the rule to that number of arguments. The rule I would like is to limit arguments to 1 or less. It doesn't have to do any analysis of the function being called.

**Comment by joelnet** [comment]
`no-ifs` is added in v1.1.1.

**Comment by joelnet** [comment]
gonna close for now. and reopen later a separate issue for `max-param-call`.
